### PR TITLE
clarify windows update module readme

### PR DESCRIPTION
**Pull request by TravisEz13**
fix module and resource name confusion. 
Add a summary of xWindowsUpdateAgent

---
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwindowsupdate/70)

### CODE REVIEW

**Comment by TravisEz13** [comment]
@kwirkykat Can you review and merge?

**Comment by johlju** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[README.md, line 13 at r1](https://reviewable.io/reviews/powershell/xwindowsupdate/70#-LClqf8v-xG2V02wmfzk:-LClqf8v-xG2V02wmfzl:b-dgd0u5) ([raw file](https://github.com/powershell/xwindowsupdate/blob/5e05426bbc233f795aac720078d90a07ab137830/README.md#L13)):*
> ```Markdown
> Windows Update (or hotfix) from a given path.
> **xWindowsUpdateAgent** will configure the source download settings for the machine,
> update notifications on the system, and can automatically initiate installation of the updates. 
> ```

Line 13 has a trailing space that fail's the tests. Could you resolve that?

*I just merged a fix for the other test that failed, so they should pass on your next push.*

---


*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwindowsupdate/70)*

**Comment by johlju** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/powershell/xwindowsupdate/70#-:-LCsgZJr7niAK-rENDNa:bg7igk9)*

**Comment by johlju** [comment]
This was merge into master :/ Need to revert this one and merge into Dev instead.  Fixing now.

**Comment by johlju** [comment]
Reverted (removed) the commit in master. New PR #72 opened against dev branch.

**Comment by TravisEz13** [comment]
sorry... the default branch is dev and I'm pretty sure I didn't change it.

**Comment by johlju** [comment]
No worries, was easy to solve. :) Not sure either why it choose master, maybe because the PR working branch was from the same repo.

**Pull request merged**
