### PR TITLE
Add xWindowsUpdate test coverage

### PR DESCRIPTION
**Pull request by TravisEz13**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwindowsupdate/48)

### CODE REVIEW

**Comment by mbreakey3** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcCZUEkC9Fecodhnvs:-KdcCZUEkC9Fecodhnvt:b-zhizku) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L2)):*
> ```PowerShell
> <#
> .Synopsis
> ```

.SYNOPSIS

Also, can you indent everything within the comment?

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 13 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcD0fRXZiFHOowak6a:-KdcD0fRXZiFHOowak6b:b5pbmwk) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L13)):*
> ```PowerShell
> 
> 
> $Global:DSCModuleName      = 'xWindowsUpdate' # Example xNetworking
> ```

these should be $script variables

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 34 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcD5q5uFjScj7Sr0DP:-KdcD5q5uFjScj7Sr0DQ:b39wkoa) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L34)):*
> ```PowerShell
> #endregion
> 
> # TODO: Other Optional Init Code Goes Here...
> ```

delete template comments

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 46 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcDBpO3x_c-kRTMqmi:-KdcDBpO3x_c-kRTMqmj:b-t0qhvo) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L46)):*
> ```PowerShell
>     InModuleScope $Global:DSCResourceName {
> 
>         #region Pester Test Initialization
> ```

delete empty regions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48)*

**Comment by TravisEz13** [comment]
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcCZUEkC9Fecodhnvs:-KdcU0512yUgqHP12D-1:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L2)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

.SYNOPSIS

Also, can you indent everything within the comment?
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 13 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcD0fRXZiFHOowak6a:-KdcU0vB701O6hEFaMvL:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L13)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

these should be $script variables
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 34 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcD5q5uFjScj7Sr0DP:-KdcU4v9w0eksw5qxynA:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L34)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

delete template comments
</blockquote></details>

Done.

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 46 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcDBpO3x_c-kRTMqmi:-KdcU1zW-orvAUyO3WCD:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L46)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

delete empty regions
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48)*

**Comment by mbreakey3** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[Tests/Unit/MSFT_xWindowsUpdate.tests.ps1, line 2 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-KdcCZUEkC9Fecodhnvs:-KdcVripiirL5MooRQfe:b-8ozkuu) ([raw file](https://github.com/powershell/xwindowsupdate/blob/43ab41829111ce8945b74b0c3cbce0378e5330ca/Tests/Unit/MSFT_xWindowsUpdate.tests.ps1#L2)):*
<details><summary><i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

SYNOPSIS should be in all caps.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48)*

**Comment by TravisEz13** [comment]
Done

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/48#-:-KdcXiXnIMWrI_Vg06kQ:bnfp4nl)*

**Pull request merged**
