### PR TITLE
Fix markdown issues

### PR DESCRIPTION
**Pull request by TravisEz13**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwindowsupdate/41)

### CODE REVIEW

**Comment by TravisEz13** [comment]
I still have these two issues to fix but let's merge these fixes until we understand these.
```
C:\projects\xwindowsupdate\README.md: 17: MD002 First header should be a top level header
C:\projects\xwindowsupdate\README.md: 1: MD041 First line in file should be a top level header
```

**Comment by johlju** [comment]
The first header needs to be moved over the build status badge to solve those lint errors.

**Comment by TravisEz13** [comment]
It is over the build badge

```
# xWindowsUpdate Module

[![Build status](https://ci.appveyor.com/api/projects/status/t4bw4lnmxy1dg3ys/branch/master?svg=true)](https://ci.appveyor.com/project/PowerShell/xwindowsupdate/branch/master)

The **xWindowsUpdate** module contains the **xHotfix** and
```

**Comment by johlju** [comment]
This is very strange. The README.md in xSQLServer looks the same and it passes. Using markdownlint extension in VS Code, does it complain to? If not there is something strange going on the markdownlint is testing the markdown in AppVeyor.

**Comment by johlju** [comment]
@TravisEz13 the README.md has encoding UTF-8 with BOM. Might be BOM that is the problem.

**Comment by TravisEz13** [comment]
No, I don't see any issues in VSCode when I installed the extension.

**Comment by TravisEz13** [comment]
That makes sense... converting it to ascii and seeing if it resolves the issue.

**Comment by johlju** [comment]
@TravisEz13 Other README.md's are just UTF-8. Like in xSQLServer.

If BOM is the problem, then maybe there should be a common test for that too. :)

**Comment by TravisEz13** [comment]
The BOM was the issue @johlju

**Comment by PlagueHO** [comment]
@johlju - that sounds like a great idea to test the BOM of all Markdown files (not just readme.md - as xNetworking and SharePointDsc have a ChangeLog.md as well).

**Comment by TravisEz13** [comment]
filed issue https://github.com/PowerShell/DscResource.Tests/issues/108

**Comment by mbreakey3** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 107 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/41#-KcV3jll3NaB5Lg4Mzy4:-KcV3jll3NaB5Lg4Mzy5:bbcmb0k) ([raw file](https://github.com/powershell/xwindowsupdate/blob/850d60248d62494e4db14ea6a60ab878dcd65300/README.md#L107)):*
> ```Markdown
> Configuration UpdateWindowsWithPath
> {
>     Node �NodeName�
> ```

the  single quote characters look like they got messed up here.

---

*[README.md, line 127 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/41#-KcV3ollQWm53dmEd9An:-KcV3ollQWm53dmEd9Ao:bbcmb0k) ([raw file](https://github.com/powershell/xwindowsupdate/blob/850d60248d62494e4db14ea6a60ab878dcd65300/README.md#L127)):*
> ```Markdown
> Configuration UpdateWindowsWithURI
> {
>     Node �NodeName�
> ```

the  single quote characters look like they got messed up here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/41)*

**Comment by TravisEz13** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[README.md, line 107 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/41#-KcV3jll3NaB5Lg4Mzy4:-KcVZe8oRBnyO1KUTekZ:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/850d60248d62494e4db14ea6a60ab878dcd65300/README.md#L107)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

the  single quote characters look like they got messed up here.
</blockquote></details>

Done.

---

*[README.md, line 127 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/41#-KcV3ollQWm53dmEd9An:-KcVZeUSo6Yf9GKvVrqG:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/850d60248d62494e4db14ea6a60ab878dcd65300/README.md#L127)):*
<details><summary><i>Previously, mbreakey3 (Mariah) wrote…</i></summary><blockquote>

the  single quote characters look like they got messed up here.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/41)*

**Pull request merged**
