### PR TITLE
added the xWindowsUpdateAgent resource with tests and readme updates

### PR DESCRIPTION
**Pull request by TravisEz13**
@HemantMahawar should review before merged

---

This change is [Reviewable](https://reviewable.io/reviews/powershell/xwindowsupdate/20)

### CODE REVIEW

**Comment by TravisEz13** [comment]
_[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof, line 3 [r2]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KEDr1N6Z7P04AuZ1m_v:-KEDr1N6Z7P04AuZ1m_w:-17830426) ([raw file](https://github.com/powershell/xwindowsupdate/blob/d5fd84b3ccf7db98389d3841f87c5b96f5bf3c67/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof#L3)):_
@HemantMahawar should review before merging

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20)_

**Comment by HemantMahawar** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

_[README.md, line 27 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMZM8TkkkTqLcnwVpp:-KHMZM8TkkkTqLcnwVpq:1619380805) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L27)):_

> ``` Markdown
> * **UpdateNow**: Indicates if the resource should trigger an update now.
> * **Category**: Indicates the categories of updates the resource should update for.  'Security', 'Important', 'Optional' (please note that security is not mutually exclusive with Important and Optional, so selecting Important may install some security updates, etc.)
> * **Notifications**: Sets the windows update agent notification setting.  Support options are 'disabled' and 'ScheduledInstallation'.  [Documentation from Windows Update](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385806%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)
> ```

Typo Support should be "Supported"
Categories should add (one or more)

---

_[README.md, line 121 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMaAaEpWmHOdQGJZjP:-KHMaAaEpWmHOdQGJZjQ:-1963452373) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L121)):_

> ``` Markdown
> Set Windows Update Agent to use Microsoft Update.
> Disables notification of future updates. 
> Install all Security and Important updates from Microsoft Update.
> ```

Call out UpdateNow = $true in the comments

---

_[README.md, line 126 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHM_WTuv4smhNHm9nIw:-KHM_WTuv4smhNHm9nIx:-1277554329) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L126)):_

> ``` Markdown
> Configuration MuSecurityImportant
> {
>     import-dscresource -ModuleName xWindowsUpdate
> ```

Fix the casing of import-dscresource
Aligning = in each resource block will be appreciated

---

_[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof, line 12 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMbiKkttCYm6wvfxvE:-KHMbiKlRkPrRjJPX-Gd:-893929871) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof#L12)):_

> ```
>         Values{"Disabled","ScheduledInstallation"}] String Notifications;
>     [Write, Description("Indicates which service Windows update agent should use.  Note: WSUS is not implemented in this resource."), ValueMap{"WindowsUpdate","MicrosoftUpdate","WSUS"}, 
>         Values{"WindowsUpdate","MicrosoftUpdate","WSUS"}] String Service;
> ```

Make it required
Call it Source

---

_[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof, line 13 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMayj6eQ9yJTKqWmQH:-KHMayj6eQ9yJTKqWmQI:-1025683440) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof#L13)):_

> ```
>     [Write, Description("Indicates which service Windows update agent should use.  Note: WSUS is not implemented in this resource."), ValueMap{"WindowsUpdate","MicrosoftUpdate","WSUS"}, 
>         Values{"WindowsUpdate","MicrosoftUpdate","WSUS"}] String Service;
>     [Required, Description("update now")] boolean UpdateNow;
> ```

Change it to write with default as $false

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20)_

**Comment by HemantMahawar** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

_[README.md, line 25 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMnRCCkgzEMO1tI_F6:-KHMnRCCkgzEMO1tI_F7:1401443593) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L25)):_

> ``` Markdown
> ### xWindowsUpdateAgent
> 
> * **UpdateNow**: Indicates if the resource should trigger an update now.
> ```

Don't have a suggestion, but  should think of better name for this property.
Currently, it doesn't clearly specify that it will sync/trigger a check with the source each time this resource runs

---

_[README.md, line 27 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMZM8TkkkTqLcnwVpp:-KHMnIteqaPHDhNBr5VQ:354794455) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L27)):_
<details><summary>

<i>Previously, HemantMahawar (Hemant Mahawar) wrote…</i></summary>



> Typo Support should be "Supported"
> Categories should add (one or more)</details>
> Default for Category should be 'Security'

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20)_

**Comment by TravisEz13** [comment]
Review status: 0 of 6 files reviewed at latest revision, 7 unresolved discussions.

---

_[README.md, line 27 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMZM8TkkkTqLcnwVpp:-KHbnbpMLI70YplLUtug:-499146009) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L27)):_
<details><summary>

<i>Previously, HemantMahawar (Hemant Mahawar) wrote…</i></summary>



> Default for Category should be 'Security'</details>
> Done.

---

_[README.md, line 121 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMaAaEpWmHOdQGJZjP:-KHbme6yuYg5zdnh5kf7:-499146045) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L121)):_
<details><summary>

<i>Previously, HemantMahawar (Hemant Mahawar) wrote…</i></summary>



> Call out UpdateNow = $true in the comments</details>
> Done

---

_[README.md, line 126 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHM_WTuv4smhNHm9nIw:-KHbmg8YSvUVXANOCkMx:676635175) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L126)):_
<details><summary>

<i>Previously, HemantMahawar (Hemant Mahawar) wrote…</i></summary>



> Fix the casing of import-dscresource
> Aligning = in each resource block will be appreciated</details>
> Done

---

_[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof, line 12 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMbiKkttCYm6wvfxvE:-KHbn7EZ687kaU8hi4Zo:676635175) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof#L12)):_
<details><summary>

<i>Previously, HemantMahawar (Hemant Mahawar) wrote…</i></summary>



> Make it required
> Call it Source</details>
> Done

---

_[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof, line 13 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMayj6eQ9yJTKqWmQH:-KHbnZUs_nTWYD_gnB3Q:676635175) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof#L13)):_
<details><summary>

<i>Previously, HemantMahawar (Hemant Mahawar) wrote…</i></summary>



> Change it to write with default as $false</details>
> Done

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20)_

**Comment by TravisEz13** [comment]
Review status: 0 of 6 files reviewed at latest revision, 6 unresolved discussions.

---

_[README.md, line 25 [r3]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KHMnRCCkgzEMO1tI_F6:-KI-8fHdLBK0vXAGbriZ:-150771947) ([raw file](https://github.com/powershell/xwindowsupdate/blob/7032d032fccf30ff78cc657eabab9ab9534cf172/README.md#L25)):_
<details><summary>

<i>Previously, HemantMahawar (Hemant Mahawar) wrote…</i></summary>



> Don't have a suggestion, but  should think of better name for this property.
> Currently, it doesn't clearly specify that it will sync/trigger a check with the source each time this resource runs</details>
> Reviewed with @brucepay 

---

_[DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof, line 3 [r2]](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20#-KEDr1N6Z7P04AuZ1m_v:-KI-8mmz-PrssIG4IXua:-499146009) ([raw file](https://github.com/powershell/xwindowsupdate/blob/d5fd84b3ccf7db98389d3841f87c5b96f5bf3c67/DscResources/MSFT_xWindowsUpdateAgent/MSFT_xWindowsUpdateAgent.schema.mof#L3)):_
<details><summary>

<i>Previously, TravisEz13 (Travis Plunk) wrote…</i></summary>



> @HemantMahawar should review before merging</details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/20)_

**Pull request merged**
