### PR TITLE
fix examples to pass common tests

### PR DESCRIPTION
**Pull request by TravisEz13**
This change is [Reviewable](https://reviewable.io/reviews/powershell/xwindowsupdate/40)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[Examples/Resources/xHotfix/Sample_xWindowsUpdateFromURI.ps1, line 9 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40#-KcRjbSpxaD3oaLZt1NK:-KcRjbSpxaD3oaLZt1NL:btpvabv) ([raw file](https://github.com/powershell/xwindowsupdate/blob/63d212432f2caf756fdbe0004d77848eaa4ab983/Examples/Resources/xHotfix/Sample_xWindowsUpdateFromURI.ps1#L9)):*
> ```PowerShell
> {
>     Import-DscResource -module xWindowsUpdate
>     xHotfix m1
> ```

My OCD sense of consistency thinks you need a CRLF before this line.

---

*[Examples/Resources/xWindowsUpdateAgent/1-SetWuaScheduledFromWu.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40#-KcRjnQ7HEjs2CvJmcUD:-KcRjnQ7HEjs2CvJmcUE:bvwcctd) ([raw file](https://github.com/powershell/xwindowsupdate/blob/63d212432f2caf756fdbe0004d77848eaa4ab983/Examples/Resources/xWindowsUpdateAgent/1-SetWuaScheduledFromWu.ps1#L1)):*
> ```PowerShell
> <#
> ```

I note this file is prefixed with a '1' - which is consistent with SharePoint/xNetworking, but the other file names aren't consistent with it. My OCD feels that we should be using the numeric prefix.

---

*[Examples/Resources/xWindowsUpdateAgent/1-SetWuaScheduledFromWu.ps1, line 11 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40#-KcRjcfmxVDzPndAALGs:-KcRjcfn8VeZewqmHIaz:btpvabv) ([raw file](https://github.com/powershell/xwindowsupdate/blob/63d212432f2caf756fdbe0004d77848eaa4ab983/Examples/Resources/xWindowsUpdateAgent/1-SetWuaScheduledFromWu.ps1#L11)):*
> ```PowerShell
> {
>     Import-DscResource -ModuleName xWindowsUpdate
>     xWindowsUpdateAgent MuSecurityImportant
> ```

My OCD sense of consistency thinks you need a CRLF before this line.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40)*

**Comment by TravisEz13** [comment]
Review status: 3 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Examples/Resources/xHotfix/Sample_xWindowsUpdateFromURI.ps1, line 9 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40#-KcRjbSpxaD3oaLZt1NK:-KcSrn4s7ckLQm8zrbR5:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/63d212432f2caf756fdbe0004d77848eaa4ab983/Examples/Resources/xHotfix/Sample_xWindowsUpdateFromURI.ps1#L9)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

My OCD sense of consistency thinks you need a CRLF before this line.
</blockquote></details>

Done.

---

*[Examples/Resources/xWindowsUpdateAgent/SetWuaScheduledFromWu.ps1, line 11 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40#-KcRjcfmxVDzPndAALGs:-KcSrrdWYo2b-tRGcmtn:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/63d212432f2caf756fdbe0004d77848eaa4ab983/Examples/Resources/xWindowsUpdateAgent/SetWuaScheduledFromWu.ps1#L11)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

My OCD sense of consistency thinks you need a CRLF before this line.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40)*

**Comment by TravisEz13** [comment]
Review status: 1 of 5 files reviewed at latest revision, 3 unresolved discussions.

---

*[Examples/Resources/xWindowsUpdateAgent/1-SetWuaScheduledFromWu.ps1, line 1 at r1](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40#-KcRjnQ7HEjs2CvJmcUD:-KcSsCdeBqwPUuQzd2Rv:b-896fix) ([raw file](https://github.com/powershell/xwindowsupdate/blob/63d212432f2caf756fdbe0004d77848eaa4ab983/Examples/Resources/xWindowsUpdateAgent/1-SetWuaScheduledFromWu.ps1#L1)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

I note this file is prefixed with a '1' - which is consistent with SharePoint/xNetworking, but the other file names aren't consistent with it. My OCD feels that we should be using the numeric prefix.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40)*

**Comment by mbreakey3** [comment]
:lgtm:

---

Reviewed 3 of 10 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/powershell/xwindowsupdate/40#-:-KcV4UPx6GTqtbazSz9E:bnfp4nl)*

**Pull request merged**
